const fs = require('fs');
const { GoogleSpreadsheet } = require('google-spreadsheet');
const { JWT } = require('google-auth-library');
const configLoader = require('./config-loader');

// Instructions tab content: each entry is [Column A, Column B]
// Section headers have text in A only; data rows have label in A, description in B.
const INSTRUCTIONS_CONTENT = [
  ['BigBarn — Google Sheets Reference', ''],
  ['', ''],
  ['This tab is auto-generated by BigBarn. Do not rename it.', ''],
  ['Each tab below controls a feature on the gym display. Column names (row 1) must match exactly.', ''],
  ['', ''],
  // ── Playlist ──
  ['═══ PLAYLIST TAB ═══', ''],
  ['Controls which YouTube videos and Instagram reels rotate on the display.', ''],
  ['', ''],
  ['Column', 'Description'],
  ['url', 'Full video URL. YouTube (youtube.com/watch?v=… or youtu.be/…) plays in the video zone. Instagram reel URLs are downloaded and played as local video files. Required — rows without a URL are skipped.'],
  ['title', 'Display name for the video. Shows in admin panel and logs. Optional — defaults to "Untitled".'],
  ['enabled', 'TRUE / FALSE — whether this video is active. Accepts: TRUE, true, yes, 1. Anything else (including blank) = disabled. Row is skipped when disabled.'],
  ['days', 'Day-of-week schedule. Comma-separated abbreviations: Mon, Tue, Wed, Thu, Fri, Sat, Sun (case-insensitive). Leave blank to play every day. Example: "Mon,Wed,Fri" plays only on those days.'],
  ['focus', 'TRUE / FALSE — highlight this video so it plays every other rotation. When any video has focus=TRUE, the display alternates: focus video → normal video → focus video → normal video. Multiple focus videos take turns in the focus slot. Leave blank or FALSE for normal rotation.'],
  ['', ''],
  ['Example rows:', ''],
  ['  url', '  https://www.youtube.com/watch?v=dQw4w9WgXcQ'],
  ['  title', '  Warm-Up Demo'],
  ['  enabled', '  TRUE'],
  ['  days', '  Mon,Wed,Fri'],
  ['  focus', '  TRUE'],
  ['', ''],
  ['How video rotation works:', ''],
  ['  No focus videos:', '  All YouTube videos play in order, then all reels, then repeat.'],
  ['  With focus videos:', '  Queue alternates — focus, normal, focus, normal… Focus videos cycle through the focus slot; everything else fills the normal slot.'],
  ['', ''],
  // ── Leaderboard ──
  ['═══ LEADERBOARD TAB ═══', ''],
  ['Displays a team competition scoreboard on the gym display.', ''],
  ['', ''],
  ['Column', 'Description'],
  ['Name', 'Athlete name. Required — rows without a name are skipped.'],
  ['Team', 'Team name (e.g., Green, Blue, Red). Required. Teams are auto-grouped and ranked by total points. Built-in team colors: Green, Blue, Red. Other team names display in gray.'],
  ['Points', 'Numeric score for this athlete. Optional — defaults to 0 if blank or not a number. Team totals are summed from member points. Teams are ranked highest-to-lowest.'],
  ['Title', 'Competition title displayed at the top (e.g., "CROSSFIT OPEN"). Only read from the FIRST row. If blank, falls back to config.yaml leaderboard.title, then "TEAM CHALLENGE".'],
  ['', ''],
  ['Behavior:', ''],
  ['  Zone auto-skips when:', '  Tab is empty, has no valid rows, or Sheets is not configured.'],
  ['  Sorting:', '  Teams ranked by total points (descending). Members within each team sorted by points (descending).'],
  ['  Refresh:', '  Data re-read every 60 seconds.'],
  ['', ''],
  // ── Announcements ──
  ['═══ ANNOUNCEMENTS TAB ═══', ''],
  ['Shows notices, alerts, and messages on the gym display.', ''],
  ['', ''],
  ['Column', 'Description'],
  ['Title', 'Announcement headline. At least one of Title or Body is required — rows with neither are skipped.'],
  ['Body', 'Announcement detail text. At least one of Title or Body is required.'],
  ['Active', 'TRUE / FALSE — whether this announcement is currently shown. Accepts: TRUE, true, yes, 1. Only active announcements appear on the display. Set to FALSE to hide without deleting.'],
  ['Priority', '"urgent" or "normal" (default). Urgent announcements display first and are visually highlighted. Any value other than "urgent" is treated as normal.'],
  ['', ''],
  ['Behavior:', ''],
  ['  Zone auto-skips when:', '  No active announcements, or Sheets is not configured.'],
  ['  Ordering:', '  Urgent announcements appear before normal ones.'],
  ['  Refresh:', '  Data re-read every 60 seconds.'],
  ['', ''],
  // ── General notes ──
  ['═══ GENERAL NOTES ═══', ''],
  ['', ''],
  ['Boolean fields', 'Any of these values count as TRUE: TRUE, true, yes, 1. Everything else (including blank) = FALSE.'],
  ['Polling', 'BigBarn polls this spreadsheet every 5 minutes (configurable). Changes may take up to 5 minutes to appear.'],
  ['Tab names', 'Tab names must match exactly: "Playlist", "Leaderboard", "Announcements". This "Instructions" tab is ignored by the system.'],
  ['Column names', 'Column names are case-sensitive and must be in row 1. Use lowercase for Playlist (url, title, enabled, days, focus). Use title case for Leaderboard (Name, Team, Points, Title) and Announcements (Title, Body, Active, Priority).'],
  ['Fallbacks', 'If Sheets is not configured or a tab is missing, BigBarn falls back to config.yaml for videos and leaderboard title. Announcements have no fallback.'],
  ['Admin panel', 'The admin panel at http://<your-ip>:3000/admin shows live status and lets you trigger an immediate Sheets sync.'],
];

class SheetsClient {
  constructor() {
    this._loadCredentials();

    this.cachedData = {};
    this.lastPoll = null;
    this.polling = false;
    this._interval = null;
    this._doc = null;
    this._parsedCreds = null;

    // Update credentials on config change
    configLoader.onConfigChange(() => {
      this._loadCredentials();
    });
  }

  _loadCredentials() {
    const config = configLoader.getConfig();
    const sheets = (config && config.sheets) || {};
    this.spreadsheetId = sheets.spreadsheet_id || '';
    this.serviceAccountEmail = sheets.service_account_email || '';
    this.credentialsFile = sheets.credentials_file || '';
    this.pollIntervalMinutes = sheets.poll_interval_minutes || 5;
    // Reset cached creds when config changes so they get re-read
    this._parsedCreds = null;
  }

  _isConfigured() {
    return !!(
      this.spreadsheetId &&
      this.spreadsheetId !== 'your_spreadsheet_id' &&
      this.credentialsFile
    );
  }

  _createAuth() {
    if (!this._parsedCreds) {
      const raw = fs.readFileSync(this.credentialsFile, 'utf8');
      this._parsedCreds = JSON.parse(raw);
    }

    return new JWT({
      email: this._parsedCreds.client_email,
      key: this._parsedCreds.private_key,
      scopes: ['https://www.googleapis.com/auth/spreadsheets']
    });
  }

  async poll() {
    if (!this._isConfigured()) return;

    try {
      const auth = this._createAuth();
      const doc = new GoogleSpreadsheet(this.spreadsheetId, auth);
      await doc.loadInfo();

      const newData = {};
      for (const sheet of doc.sheetsByIndex) {
        if (sheet.title === 'Instructions') continue; // Skip documentation tab
        const rows = await sheet.getRows();
        newData[sheet.title] = rows.map(row => row.toObject());
      }

      this.cachedData = newData;
      this.lastPoll = Date.now();
      console.log(`[Sheets] Poll complete: ${Object.keys(newData).length} tab(s) — ${Object.keys(newData).join(', ')}`);
    } catch (err) {
      console.warn(`[Sheets] Poll failed (keeping stale cache): ${err.message}`);
    }
  }

  startPolling() {
    if (!this._isConfigured()) {
      console.log('[Sheets] Not configured, skipping');
      return;
    }

    // Delay initial poll by 5 seconds to avoid cold-start quota spike
    setTimeout(() => {
      this.poll()
        .then(() => {
          // Create/update Instructions tab after first successful poll
          this.writeInstructionsTab().catch(err => console.warn(`[Sheets] Instructions tab error: ${err.message}`));
        })
        .catch(err => console.warn(`[Sheets] Poll error: ${err.message}`));
    }, 5000);

    this._interval = setInterval(() => {
      this.poll().catch(err => console.warn(`[Sheets] Poll error: ${err.message}`));
    }, this.pollIntervalMinutes * 60 * 1000);

    this.polling = true;
    console.log(`[Sheets] Polling started (every ${this.pollIntervalMinutes}min)`);
  }

  stopPolling() {
    if (this._interval) {
      clearInterval(this._interval);
      this._interval = null;
    }
    this.polling = false;
  }

  /**
   * Create or update the "Instructions" tab with documentation for all tabs.
   * Safe to call multiple times — overwrites existing content.
   */
  async writeInstructionsTab() {
    if (!this._isConfigured()) return;

    try {
      const auth = this._createAuth();
      const doc = new GoogleSpreadsheet(this.spreadsheetId, auth);
      await doc.loadInfo();

      // Find or create the Instructions sheet
      let sheet = doc.sheetsByTitle['Instructions'];
      if (!sheet) {
        sheet = await doc.addSheet({ title: 'Instructions' });
      }

      // Clear existing content and resize
      await sheet.clear();
      await sheet.resize({ rowCount: INSTRUCTIONS_CONTENT.length + 1, columnCount: 2 });

      // Load cells to write free-form content (2 columns: label + description)
      await sheet.loadCells({
        startRowIndex: 0,
        endRowIndex: INSTRUCTIONS_CONTENT.length,
        startColumnIndex: 0,
        endColumnIndex: 2
      });

      for (let i = 0; i < INSTRUCTIONS_CONTENT.length; i++) {
        const cellA = sheet.getCell(i, 0);
        const cellB = sheet.getCell(i, 1);
        cellA.value = INSTRUCTIONS_CONTENT[i][0] || '';
        cellB.value = INSTRUCTIONS_CONTENT[i][1] || '';

        // Bold styling for section headers (rows where col B is empty and col A has text)
        if (INSTRUCTIONS_CONTENT[i][0] && !INSTRUCTIONS_CONTENT[i][1]) {
          cellA.textFormat = { bold: true, fontSize: 11 };
        }
        // Title row
        if (i === 0) {
          cellA.textFormat = { bold: true, fontSize: 14 };
        }
      }

      await sheet.saveUpdatedCells();

      // Set column widths for readability
      await sheet.updateDimensionProperties('COLUMNS', { pixelSize: 320 }, { startIndex: 0, endIndex: 1 });
      await sheet.updateDimensionProperties('COLUMNS', { pixelSize: 700 }, { startIndex: 1, endIndex: 2 });

      console.log('[Sheets] Instructions tab created/updated');
    } catch (err) {
      console.warn(`[Sheets] Failed to write Instructions tab: ${err.message}`);
    }
  }

  getTabData(tabName) {
    return this.cachedData[tabName] || [];
  }

  getTabNames() {
    return Object.keys(this.cachedData);
  }

  getStatus() {
    return {
      configured: this._isConfigured(),
      polling: this.polling,
      lastPoll: this.lastPoll,
      tabs: this.getTabNames()
    };
  }
}

// Singleton instance
module.exports = new SheetsClient();
