const fs = require('fs');
const { GoogleSpreadsheet } = require('google-spreadsheet');
const { JWT } = require('google-auth-library');
const configLoader = require('./config-loader');

// Instructions tab content: each entry is [Column A, Column B]
// Section headers have text in A only; data rows have label in A, description in B.
const INSTRUCTIONS_CONTENT = [
  ['BigBarn — Google Sheets Reference', ''],
  ['', ''],
  ['This tab is auto-generated by BigBarn. Do not rename it.', ''],
  ['Each tab below controls a feature on the gym display. Column names (row 1) must match exactly.', ''],
  ['', ''],
  // ── Playlist ──
  ['═══ PLAYLIST TAB ═══', ''],
  ['Controls which YouTube videos and Instagram reels rotate on the display.', ''],
  ['', ''],
  ['Column', 'Description'],
  ['url', 'Full video URL. YouTube (youtube.com/watch?v=… or youtu.be/…) plays in the video zone. Instagram reel URLs are downloaded and played as local video files. Required — rows without a URL are skipped.'],
  ['title', 'Display name for the video. Shows in admin panel and logs. Optional — defaults to "Untitled".'],
  ['enabled', 'TRUE / FALSE — whether this video is active. Accepts: TRUE, true, yes, 1. Anything else (including blank) = disabled. Row is skipped when disabled.'],
  ['days', 'Day-of-week schedule. Comma-separated abbreviations: Mon, Tue, Wed, Thu, Fri, Sat, Sun (case-insensitive). Leave blank to play every day. Example: "Mon,Wed,Fri" plays only on those days.'],
  ['focus', 'TRUE / FALSE — highlight this video so it plays every other rotation. When any video has focus=TRUE, the display alternates: focus video → normal video → focus video → normal video. Multiple focus videos take turns in the focus slot. Leave blank or FALSE for normal rotation.'],
  ['', ''],
  ['Example rows:', ''],
  ['  url', '  https://www.youtube.com/watch?v=dQw4w9WgXcQ'],
  ['  title', '  Warm-Up Demo'],
  ['  enabled', '  TRUE'],
  ['  days', '  Mon,Wed,Fri'],
  ['  focus', '  TRUE'],
  ['', ''],
  ['How video rotation works:', ''],
  ['  No focus videos:', '  All YouTube videos play in order, then all reels, then repeat.'],
  ['  With focus videos:', '  Queue alternates — focus, normal, focus, normal… Focus videos cycle through the focus slot; everything else fills the normal slot.'],
  ['', ''],
  // ── Leaderboard ──
  ['═══ LEADERBOARD TAB ═══', ''],
  ['Displays a team competition scoreboard on the gym display.', ''],
  ['', ''],
  ['Column', 'Description'],
  ['Name', 'Athlete name. Required — rows without a name are skipped.'],
  ['Team', 'Team name (e.g., Green, Blue, Red). Required. Teams are auto-grouped and ranked by total points. Built-in team colors: Green, Blue, Red. Other team names display in gray.'],
  ['Points', 'Numeric score for this athlete. Optional — defaults to 0 if blank or not a number. Team totals are summed from member points. Teams are ranked highest-to-lowest.'],
  ['Title', 'Competition title displayed at the top (e.g., "CROSSFIT OPEN"). Only read from the FIRST row. If blank, falls back to config.yaml leaderboard.title, then "TEAM CHALLENGE".'],
  ['', ''],
  ['Behavior:', ''],
  ['  Zone auto-skips when:', '  Tab is empty, has no valid rows, or Sheets is not configured.'],
  ['  Sorting:', '  Teams ranked by total points (descending). Members within each team sorted by points (descending).'],
  ['  Refresh:', '  Data re-read every 60 seconds.'],
  ['', ''],
  // ── Announcements ──
  ['═══ ANNOUNCEMENTS TAB ═══', ''],
  ['Shows notices, alerts, and messages on the gym display.', ''],
  ['', ''],
  ['Column', 'Description'],
  ['Title', 'Announcement headline. At least one of Title or Body is required — rows with neither are skipped.'],
  ['Body', 'Announcement detail text. At least one of Title or Body is required.'],
  ['Active', 'TRUE / FALSE — whether this announcement is currently shown. Accepts: TRUE, true, yes, 1. Only active announcements appear on the display. Set to FALSE to hide without deleting.'],
  ['Priority', '"urgent" or "normal" (default). Urgent announcements display first and are visually highlighted. Any value other than "urgent" is treated as normal.'],
  ['', ''],
  ['Behavior:', ''],
  ['  Zone auto-skips when:', '  No active announcements, or Sheets is not configured.'],
  ['  Ordering:', '  Urgent announcements appear before normal ones.'],
  ['  Refresh:', '  Data re-read every 60 seconds.'],
  ['', ''],
  // ── LiveEvent ──
  ['═══ LIVEEVENT TAB ═══', ''],
  ['Optional — schedule a YouTube Live takeover of the gym display.', ''],
  ['When a live event is active, the display switches to fullscreen YouTube Live. Normal rotation resumes automatically when the event ends.', ''],
  ['', ''],
  ['Column', 'Description'],
  ['Title', 'Event display name. Shows briefly as an overlay on the live stream. Example: "CrossFit Games 2026 Finals".'],
  ['URL', 'YouTube Live or video URL. Supports youtube.com/watch?v=, youtu.be/, youtube.com/live/ formats. Example: "https://youtube.com/watch?v=abc".'],
  ['Start', 'Event start time in YYYY-MM-DD HH:MM format. Uses the gym\'s configured timezone. Example: "2026-03-15 09:00".'],
  ['End', 'Event end time in YYYY-MM-DD HH:MM format. Uses the gym\'s configured timezone. Example: "2026-03-15 17:00".'],
  ['Enabled', 'TRUE to activate, FALSE to disable. Only enabled events will trigger the live takeover. Accepts: TRUE, true, yes, 1.'],
  ['', ''],
  ['Behavior:', ''],
  ['  Takeover:', '  When a live event is active (current time between Start and End), the display immediately switches to fullscreen YouTube Live.'],
  ['  Auto-resume:', '  When the event time window ends, normal zone rotation resumes automatically from where it left off.'],
  ['  Multiple events:', '  If multiple events overlap, the first enabled match (top row) wins.'],
  ['  Polling:', '  Live event data is checked every 60 seconds.'],
  ['', ''],
  // ── Screens ──
  ['═══ SCREENS TAB ═══', ''],
  ['Controls which display zones are active in the rotation. Disable a zone to remove it from the display without deleting its data.', ''],
  ['', ''],
  ['Column', 'Description'],
  ['Screen', 'Zone name. Must match exactly: wod, video, roster, leaderboard, announcements. Do not edit this column.'],
  ['Enabled', 'TRUE / FALSE — whether this zone appears in the rotation. Accepts: TRUE, true, yes, 1. Set to FALSE to hide the zone. Blank = disabled.'],
  ['Description', 'What this zone shows. For reference only — not used by the system.'],
  ['', ''],
  ['Behavior:', ''],
  ['  Disabled zones:', '  Removed from rotation entirely. The display skips them as if they don\'t exist.'],
  ['  All zones disabled:', '  If every zone is disabled, the system ignores the Screens tab and shows all zones (safety fallback).'],
  ['  Refresh:', '  Changes take effect on the next Sheets poll (up to 5 minutes). Use the admin panel to trigger an immediate sync.'],
  ['', ''],
  // ── General notes ──
  ['═══ GENERAL NOTES ═══', ''],
  ['', ''],
  ['Boolean fields', 'Any of these values count as TRUE: TRUE, true, yes, 1. Everything else (including blank) = FALSE.'],
  ['Polling', 'BigBarn polls this spreadsheet every 5 minutes (configurable). Changes may take up to 5 minutes to appear.'],
  ['Tab names', 'Tab names must match exactly: "Playlist", "Leaderboard", "Announcements", "LiveEvent", "Screens". This "Instructions" tab is ignored by the system.'],
  ['Column names', 'Column names are case-sensitive and must be in row 1. Use lowercase for Playlist (url, title, enabled, days, focus). Use title case for Leaderboard (Name, Team, Points, Title) and Announcements (Title, Body, Active, Priority).'],
  ['Fallbacks', 'If Sheets is not configured or a tab is missing, BigBarn falls back to config.yaml for videos and leaderboard title. Announcements have no fallback.'],
  ['Admin panel', 'The admin panel at http://<your-ip>:3000/admin shows live status and lets you trigger an immediate Sheets sync.'],
  ['', ''],
  // ── Timing ──
  ['═══ TIMING TAB ═══', ''],
  ['Controls how long each zone displays and how often services poll for updates.', ''],
  ['Edit the Value column to change timing. Changes take effect on the next Sheets poll (up to 5 minutes).', ''],
  ['', ''],
  ['Column', 'Description'],
  ['Setting', 'The timing parameter name. Do not edit — these must match exactly.'],
  ['Value', 'The numeric value to use. Edit this column to change timing.'],
  ['Unit', 'The unit of measurement (seconds or minutes). Do not edit.'],
  ['Description', 'What this setting controls. Do not edit.'],
  ['', ''],
  ['Zone Display Durations:', ''],
  ['  wod_duration', 'How long the WOD (Workout of the Day) zone displays before rotating. Default: 120 seconds.'],
  ['  video_fallback', 'Maximum time for a video if play_full is on, or exact duration if off. Default: 180 seconds.'],
  ['  roster_duration', 'How long the class roster zone displays. Default: 60 seconds.'],
  ['  leaderboard_duration', 'How long the leaderboard zone displays. Default: 90 seconds.'],
  ['  announcements_duration', 'How long the announcements zone displays. Default: 60 seconds.'],
  ['', ''],
  ['Roster Boost (near class time):', ''],
  ['  boost_before_class', 'Minutes before a class starts to activate roster boost. Default: 15 minutes.'],
  ['  boost_frequency', 'How often roster appears during boost (2 = every other zone). Default: 2.'],
  ['', ''],
  ['Service Polling:', ''],
  ['  sheets_poll_interval', 'How often to check this spreadsheet for changes. Default: 5 minutes.'],
  ['  mindbody_poll_interval', 'How often to check MindBody for class schedule updates. Default: 5 minutes.'],
  ['  wod_refresh_interval', 'How often to re-capture the WOD screenshot. Default: 30 minutes.'],
  ['  instagram_fetch_interval', 'How often to check for new Instagram reels. Default: 60 minutes.'],
  ['  instagram_min_display', 'Minimum time to show an Instagram reel. Default: 30 seconds.'],
  ['', ''],
  ['System Schedule:', ''],
  ['  screen_off_hour', 'Hour (24h format) to turn off the TV via HDMI-CEC. Default: 21 (9 PM).'],
  ['  screen_on_hour', 'Hour (24h format) to turn on the TV. Supports HH:MM format. Default: 04:30.'],
  ['', ''],
  ['Notes:', ''],
  ['  • Only edit the Value column. Changes to Setting or Unit columns may break the system.', ''],
  ['  • Values must be positive numbers. Invalid values are ignored (previous value kept).', ''],
  ['  • The Timing tab is created with current values from config.yaml. Sheet values override config.yaml.', ''],
];

class SheetsClient {
  constructor() {
    this._loadCredentials();

    this.cachedData = {};
    this.lastPoll = null;
    this.polling = false;
    this._interval = null;
    this._doc = null;
    this._parsedCreds = null;

    // Update credentials on config change
    configLoader.onConfigChange(() => {
      this._loadCredentials();
    });
  }

  _loadCredentials() {
    const config = configLoader.getConfig();
    const sheets = (config && config.sheets) || {};
    this.spreadsheetId = sheets.spreadsheet_id || '';
    this.serviceAccountEmail = sheets.service_account_email || '';
    this.credentialsFile = sheets.credentials_file || '';
    this.pollIntervalMinutes = sheets.poll_interval_minutes || 5;
    // Reset cached creds when config changes so they get re-read
    this._parsedCreds = null;
  }

  _isConfigured() {
    return !!(
      this.spreadsheetId &&
      this.spreadsheetId !== 'your_spreadsheet_id' &&
      this.credentialsFile
    );
  }

  _createAuth() {
    if (!this._parsedCreds) {
      const raw = fs.readFileSync(this.credentialsFile, 'utf8');
      this._parsedCreds = JSON.parse(raw);
    }

    return new JWT({
      email: this._parsedCreds.client_email,
      key: this._parsedCreds.private_key,
      scopes: ['https://www.googleapis.com/auth/spreadsheets']
    });
  }

  async poll() {
    if (!this._isConfigured()) return;

    try {
      const auth = this._createAuth();
      const doc = new GoogleSpreadsheet(this.spreadsheetId, auth);
      await doc.loadInfo();

      const newData = {};
      for (const sheet of doc.sheetsByIndex) {
        if (sheet.title === 'Instructions') continue; // Skip documentation tab
        const rows = await sheet.getRows();
        newData[sheet.title] = rows.map(row => row.toObject());
      }

      this.cachedData = newData;
      this.lastPoll = Date.now();
      console.log(`[Sheets] Poll complete: ${Object.keys(newData).length} tab(s) — ${Object.keys(newData).join(', ')}`);

      // Apply timing overrides from the Timing tab (if present)
      this._applyTimingFromSheet();
    } catch (err) {
      console.warn(`[Sheets] Poll failed (keeping stale cache): ${err.message}`);
    }
  }

  startPolling() {
    if (!this._isConfigured()) {
      console.log('[Sheets] Not configured, skipping');
      return;
    }

    // Delay initial poll by 5 seconds to avoid cold-start quota spike
    setTimeout(() => {
      this.poll()
        .then(() => {
          // Create/update Instructions tab after first successful poll
          this.writeInstructionsTab().catch(err => console.warn(`[Sheets] Instructions tab error: ${err.message}`));
        })
        .catch(err => console.warn(`[Sheets] Poll error: ${err.message}`));
    }, 5000);

    this._interval = setInterval(() => {
      this.poll().catch(err => console.warn(`[Sheets] Poll error: ${err.message}`));
    }, this.pollIntervalMinutes * 60 * 1000);

    this.polling = true;
    console.log(`[Sheets] Polling started (every ${this.pollIntervalMinutes}min)`);
  }

  stopPolling() {
    if (this._interval) {
      clearInterval(this._interval);
      this._interval = null;
    }
    this.polling = false;
  }

  /**
   * Create or update the "Instructions" tab with documentation for all tabs.
   * Safe to call multiple times — overwrites existing content.
   */
  async writeInstructionsTab() {
    if (!this._isConfigured()) return;

    try {
      const auth = this._createAuth();
      const doc = new GoogleSpreadsheet(this.spreadsheetId, auth);
      await doc.loadInfo();

      // Find or create the Instructions sheet
      let sheet = doc.sheetsByTitle['Instructions'];
      if (!sheet) {
        sheet = await doc.addSheet({ title: 'Instructions' });
      }

      // Clear existing content and resize
      await sheet.clear();
      await sheet.resize({ rowCount: INSTRUCTIONS_CONTENT.length + 1, columnCount: 2 });

      // Load cells to write free-form content (2 columns: label + description)
      await sheet.loadCells({
        startRowIndex: 0,
        endRowIndex: INSTRUCTIONS_CONTENT.length,
        startColumnIndex: 0,
        endColumnIndex: 2
      });

      for (let i = 0; i < INSTRUCTIONS_CONTENT.length; i++) {
        const cellA = sheet.getCell(i, 0);
        const cellB = sheet.getCell(i, 1);
        cellA.value = INSTRUCTIONS_CONTENT[i][0] || '';
        cellB.value = INSTRUCTIONS_CONTENT[i][1] || '';

        // Bold styling for section headers (rows where col B is empty and col A has text)
        if (INSTRUCTIONS_CONTENT[i][0] && !INSTRUCTIONS_CONTENT[i][1]) {
          cellA.textFormat = { bold: true, fontSize: 11 };
        }
        // Title row
        if (i === 0) {
          cellA.textFormat = { bold: true, fontSize: 14 };
        }
      }

      await sheet.saveUpdatedCells();

      // Set column widths for readability
      await sheet.updateDimensionProperties('COLUMNS', { pixelSize: 320 }, { startIndex: 0, endIndex: 1 });
      await sheet.updateDimensionProperties('COLUMNS', { pixelSize: 700 }, { startIndex: 1, endIndex: 2 });

      console.log('[Sheets] Instructions tab created/updated');

      // Create/update Timing tab with current config values
      await this._writeTimingTab(doc);

      // Create Screens tab with defaults if it doesn't exist
      await this._writeScreensTab(doc);

      // Create LiveEvent tab with headers if it doesn't exist
      if (!doc.sheetsByTitle['LiveEvent']) {
        const liveSheet = await doc.addSheet({
          title: 'LiveEvent',
          headerValues: ['Title', 'URL', 'Start', 'End', 'Enabled']
        });
        console.log('[Sheets] LiveEvent tab created with headers');
      }
    } catch (err) {
      console.warn(`[Sheets] Failed to write Instructions tab: ${err.message}`);
    }
  }

  /**
   * Build the timing rows from current config values.
   */
  _getTimingRows() {
    const config = configLoader.getConfig() || {};
    const zones = config.zones || {};
    const mb = config.mindbody || {};
    const sheets = config.sheets || {};
    const wod = config.wodscreen || {};
    const ig = config.instagram || {};
    const sys = config.system || {};

    return [
      ['Setting', 'Value', 'Unit', 'Description'],
      ['wod_duration', (zones.wod && zones.wod.duration_seconds) || 120, 'seconds', 'How long the WOD zone displays'],
      ['video_fallback', (zones.video && zones.video.fallback_seconds) || 180, 'seconds', 'Video zone max/fallback duration'],
      ['roster_duration', (zones.roster && zones.roster.duration_seconds) || 60, 'seconds', 'How long the roster zone displays'],
      ['leaderboard_duration', (zones.leaderboard && zones.leaderboard.duration_seconds) || 90, 'seconds', 'How long the leaderboard zone displays'],
      ['announcements_duration', (zones.announcements && zones.announcements.duration_seconds) || 60, 'seconds', 'How long the announcements zone displays'],
      ['boost_before_class', (zones.roster && zones.roster.boost_before_class_minutes) || 15, 'minutes', 'Minutes before class to activate roster boost'],
      ['boost_frequency', (zones.roster && zones.roster.boost_frequency) || 2, 'x', 'How often roster appears during boost (2 = every other zone)'],
      ['sheets_poll_interval', sheets.poll_interval_minutes || 5, 'minutes', 'How often to poll this spreadsheet'],
      ['mindbody_poll_interval', mb.poll_interval_minutes || 5, 'minutes', 'How often to poll MindBody schedule'],
      ['wod_refresh_interval', wod.refresh_interval_minutes || 30, 'minutes', 'How often to re-capture the WOD'],
      ['instagram_fetch_interval', (ig.fetch_interval_minutes) || 60, 'minutes', 'How often to fetch new Instagram reels'],
      ['instagram_min_display', (ig.min_display_seconds) || 30, 'seconds', 'Minimum display time for reels'],
      ['screen_off_time', sys.screen_off_start || '21:00', 'HH:MM', 'Time to turn off TV (24h format)'],
      ['screen_on_time', sys.screen_off_end || '04:30', 'HH:MM', 'Time to turn on TV (24h format)'],
    ];
  }

  /**
   * Create the Timing tab if it doesn't exist, populated with current config values.
   * If it already exists, leave it alone (user may have edited values).
   */
  async _writeTimingTab(doc) {
    try {
      if (doc.sheetsByTitle['Timing']) {
        return; // Already exists — don't overwrite user edits
      }

      const rows = this._getTimingRows();
      const headers = rows[0];
      const sheet = await doc.addSheet({
        title: 'Timing',
        headerValues: headers
      });

      // Add data rows (skip header — already set by addSheet)
      const dataRows = rows.slice(1).map(row => ({
        Setting: row[0],
        Value: row[1],
        Unit: row[2],
        Description: row[3]
      }));
      await sheet.addRows(dataRows);

      // Set column widths
      await sheet.updateDimensionProperties('COLUMNS', { pixelSize: 220 }, { startIndex: 0, endIndex: 1 });
      await sheet.updateDimensionProperties('COLUMNS', { pixelSize: 100 }, { startIndex: 1, endIndex: 2 });
      await sheet.updateDimensionProperties('COLUMNS', { pixelSize: 80 }, { startIndex: 2, endIndex: 3 });
      await sheet.updateDimensionProperties('COLUMNS', { pixelSize: 400 }, { startIndex: 3, endIndex: 4 });

      console.log('[Sheets] Timing tab created with current config values');
    } catch (err) {
      console.warn(`[Sheets] Failed to create Timing tab: ${err.message}`);
    }
  }

  /**
   * Create the Screens tab if it doesn't exist, populated with all zones enabled.
   * If it already exists, leave it alone (user may have edited values).
   */
  async _writeScreensTab(doc) {
    try {
      if (doc.sheetsByTitle['Screens']) {
        return; // Already exists — don't overwrite user edits
      }

      const config = configLoader.getConfig() || {};
      const zones = config.zones || {};
      const order = zones.rotation_order || ['wod', 'video', 'roster', 'leaderboard', 'announcements'];

      const descriptions = {
        wod: 'Workout of the Day from Beyond The Whiteboard',
        video: 'YouTube videos and Instagram reels',
        roster: 'Live class athlete check-ins from MindBody',
        leaderboard: 'Team competition scoreboard',
        announcements: 'Gym notices and alerts'
      };

      const sheet = await doc.addSheet({
        title: 'Screens',
        headerValues: ['Screen', 'Enabled', 'Description']
      });

      const dataRows = order.map(zone => ({
        Screen: zone,
        Enabled: 'TRUE',
        Description: descriptions[zone] || zone
      }));
      await sheet.addRows(dataRows);

      // Set column widths
      await sheet.updateDimensionProperties('COLUMNS', { pixelSize: 160 }, { startIndex: 0, endIndex: 1 });
      await sheet.updateDimensionProperties('COLUMNS', { pixelSize: 100 }, { startIndex: 1, endIndex: 2 });
      await sheet.updateDimensionProperties('COLUMNS', { pixelSize: 400 }, { startIndex: 2, endIndex: 3 });

      console.log('[Sheets] Screens tab created with all zones enabled');
    } catch (err) {
      console.warn(`[Sheets] Failed to create Screens tab: ${err.message}`);
    }
  }

  /**
   * Apply timing values from the Timing sheet tab to config.yaml.
   * Only applies valid numeric changes; ignores invalid or unchanged values.
   */
  _applyTimingFromSheet() {
    const timingData = this.cachedData['Timing'];
    if (!timingData || timingData.length === 0) return;

    const config = configLoader.getConfig() || {};
    const updates = {};
    let changed = false;

    for (const row of timingData) {
      const setting = (row.Setting || '').trim();
      const rawValue = (row.Value || '').toString().trim();
      if (!setting || !rawValue) continue;

      // Parse numeric values (allow HH:MM for screen times)
      const numValue = Number(rawValue);
      const isTime = /^\d{1,2}:\d{2}$/.test(rawValue);

      if (!isTime && (isNaN(numValue) || numValue <= 0)) continue;

      switch (setting) {
        case 'wod_duration': {
          const current = (config.zones && config.zones.wod && config.zones.wod.duration_seconds) || 120;
          if (numValue !== current) {
            if (!updates.zones) updates.zones = {};
            if (!updates.zones.wod) updates.zones.wod = {};
            updates.zones.wod.duration_seconds = numValue;
            changed = true;
          }
          break;
        }
        case 'video_fallback': {
          const current = (config.zones && config.zones.video && config.zones.video.fallback_seconds) || 180;
          if (numValue !== current) {
            if (!updates.zones) updates.zones = {};
            if (!updates.zones.video) updates.zones.video = {};
            updates.zones.video.fallback_seconds = numValue;
            changed = true;
          }
          break;
        }
        case 'roster_duration': {
          const current = (config.zones && config.zones.roster && config.zones.roster.duration_seconds) || 60;
          if (numValue !== current) {
            if (!updates.zones) updates.zones = {};
            if (!updates.zones.roster) updates.zones.roster = {};
            updates.zones.roster.duration_seconds = numValue;
            changed = true;
          }
          break;
        }
        case 'leaderboard_duration': {
          const current = (config.zones && config.zones.leaderboard && config.zones.leaderboard.duration_seconds) || 90;
          if (numValue !== current) {
            if (!updates.zones) updates.zones = {};
            if (!updates.zones.leaderboard) updates.zones.leaderboard = {};
            updates.zones.leaderboard.duration_seconds = numValue;
            changed = true;
          }
          break;
        }
        case 'announcements_duration': {
          const current = (config.zones && config.zones.announcements && config.zones.announcements.duration_seconds) || 60;
          if (numValue !== current) {
            if (!updates.zones) updates.zones = {};
            if (!updates.zones.announcements) updates.zones.announcements = {};
            updates.zones.announcements.duration_seconds = numValue;
            changed = true;
          }
          break;
        }
        case 'boost_before_class': {
          const current = (config.zones && config.zones.roster && config.zones.roster.boost_before_class_minutes) || 15;
          if (numValue !== current) {
            if (!updates.zones) updates.zones = {};
            if (!updates.zones.roster) updates.zones.roster = {};
            updates.zones.roster.boost_before_class_minutes = numValue;
            changed = true;
          }
          break;
        }
        case 'boost_frequency': {
          const current = (config.zones && config.zones.roster && config.zones.roster.boost_frequency) || 2;
          if (numValue !== current) {
            if (!updates.zones) updates.zones = {};
            if (!updates.zones.roster) updates.zones.roster = {};
            updates.zones.roster.boost_frequency = numValue;
            changed = true;
          }
          break;
        }
        case 'sheets_poll_interval': {
          const current = (config.sheets && config.sheets.poll_interval_minutes) || 5;
          if (numValue !== current) {
            if (!updates.sheets) updates.sheets = {};
            updates.sheets.poll_interval_minutes = numValue;
            changed = true;
          }
          break;
        }
        case 'mindbody_poll_interval': {
          const current = (config.mindbody && config.mindbody.poll_interval_minutes) || 5;
          if (numValue !== current) {
            if (!updates.mindbody) updates.mindbody = {};
            updates.mindbody.poll_interval_minutes = numValue;
            changed = true;
          }
          break;
        }
        case 'wod_refresh_interval': {
          const current = (config.wodscreen && config.wodscreen.refresh_interval_minutes) || 30;
          if (numValue !== current) {
            if (!updates.wodscreen) updates.wodscreen = {};
            updates.wodscreen.refresh_interval_minutes = numValue;
            changed = true;
          }
          break;
        }
        case 'instagram_fetch_interval': {
          const current = (config.instagram && config.instagram.fetch_interval_minutes) || 60;
          if (numValue !== current) {
            if (!updates.instagram) updates.instagram = {};
            updates.instagram.fetch_interval_minutes = numValue;
            changed = true;
          }
          break;
        }
        case 'instagram_min_display': {
          const current = (config.instagram && config.instagram.min_display_seconds) || 30;
          if (numValue !== current) {
            if (!updates.instagram) updates.instagram = {};
            updates.instagram.min_display_seconds = numValue;
            changed = true;
          }
          break;
        }
        case 'screen_off_time': {
          if (isTime && rawValue !== (config.system && config.system.screen_off_start || '21:00')) {
            if (!updates.system) updates.system = {};
            updates.system.screen_off_start = rawValue;
            changed = true;
          }
          break;
        }
        case 'screen_on_time': {
          if (isTime && rawValue !== (config.system && config.system.screen_off_end || '04:30')) {
            if (!updates.system) updates.system = {};
            updates.system.screen_off_end = rawValue;
            changed = true;
          }
          break;
        }
      }
    }

    if (changed) {
      try {
        configLoader.saveConfig(updates);
        console.log('[Sheets] Timing values applied to config:', JSON.stringify(updates));
      } catch (err) {
        console.warn(`[Sheets] Failed to apply timing values: ${err.message}`);
      }
    }
  }

  /**
   * Returns a Set of zone names that are disabled via the Screens tab.
   * If the Screens tab doesn't exist or all zones are disabled (safety), returns empty Set.
   */
  getDisabledZones() {
    const screensData = this.cachedData['Screens'];
    if (!screensData || screensData.length === 0) return new Set();

    const disabled = new Set();
    const allZones = new Set();

    for (const row of screensData) {
      const screen = (row.Screen || '').trim().toLowerCase();
      if (!screen) continue;
      allZones.add(screen);

      const enabled = (row.Enabled || '').toString().trim().toLowerCase();
      const isEnabled = ['true', 'yes', '1'].includes(enabled);
      if (!isEnabled) {
        disabled.add(screen);
      }
    }

    // Safety fallback: if ALL zones disabled, ignore the tab entirely
    if (disabled.size > 0 && disabled.size >= allZones.size) {
      console.warn('[Sheets] All zones disabled in Screens tab — ignoring (safety fallback)');
      return new Set();
    }

    if (disabled.size > 0) {
      console.log(`[Sheets] Disabled zones from Screens tab: ${[...disabled].join(', ')}`);
    }

    return disabled;
  }

  getTabData(tabName) {
    return this.cachedData[tabName] || [];
  }

  getTabNames() {
    return Object.keys(this.cachedData);
  }

  getStatus() {
    return {
      configured: this._isConfigured(),
      polling: this.polling,
      lastPoll: this.lastPoll,
      tabs: this.getTabNames()
    };
  }
}

// Singleton instance
module.exports = new SheetsClient();
